esphome:
  name: waterlevel
  friendly_name: WaterLevel

esp32:
  board: lolin32_lite
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: GPIO23
  scl: GPIO19
  scan: true

external_components:
  source:
    type: git
    url: https://github.com/shyd/esphome-components

sensor:
  - platform: water_level_sensor
    name: "Water Level"
    update_interval: 60s
